### ISSUE TITLE
Auto-find the workshop homepage/game ID does not work

### ISSUE THREAD

**Issue by githubromankolo** [imwaitingnow/WorkshopDL-installer#3]
I tried to enable Auto-find the workshop homepage/game ID and it doesn't work. Tried to Reset Config, still doesn't work. Editing the Config File doesn't help either. This function worked before the fork. I use the latest release.

**Comment by imwaitingnow** [comment]
thanks for letting me know i stupidly built the program using the wrong version of clicksteam will be fixed shortly

**Comment by imwaitingnow** [comment]
issue fixed in latest release

**Comment by githubromankolo** [comment]
thanks for the fix 👍
